# Imagen base
FROM python:3.11-slim

# Crear directorio de trabajo
WORKDIR /app

# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y gcc libpq-dev && rm -rf /var/lib/apt/lists/*

# Copiar dependencias
COPY requirements.txt .

# Instalar paquetes de Python
RUN pip install --no-cache-dir -r requirements.txt gunicorn

# Copiar código
COPY . .

# Exponer puerto
EXPOSE 8000

# Comando para correr Django con Gunicorn
CMD ["gunicorn", "backend.wsgi:application", "--bind", "0.0.0.0:8000"]
